### ISSUE TITLE
Random.Next has an overload that takes only one parameter

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/GuessingGame#2]
https://github.com/geordzNZ/GuessingGame/blob/1b257f380ea4d48b6d90754f000e9c84222d6312/GuessingGame/Program.cs#L19
This will generate you a number between 0 and 100 which can be re-written with just
```target.Next(MAX_TARGET + 1);```
https://learn.microsoft.com/en-us/dotnet/api/system.random.next?view=net-8.0#system-random-next(system-int32)

But on the other hand, it is more maintainable the way you wrote it so that you can modify the behaviour of your program by just setting the constants MIN_ and MAX_TARGET 👍 

I just wanted to point out that there are additional overloads of the Random.Next functions that you could take a look,
but you can close this issue after you read it

**Comment by geordzNZ** [comment]
OK noted yeah, 
I think that, seeing as I found a version of generating a number, I stopped there ... should have kept reading along.
