### ISSUE TITLE
interesting approach

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/GuessingGame#4]
https://github.com/geordzNZ/GuessingGame/blob/1b257f380ea4d48b6d90754f000e9c84222d6312/GuessingGame/Program.cs#L44
that you calculate the difference of both values and check if it is positive :D

But I think it would be more readable if you just compare if the value is larger like
```if (targetNumber > guessedNumber)```

or even the other way around which make it more in sync with the output;
```
if (guessedNumber < targetNumber)
Console.Write($"\n\tYour guess was TOO LOW ");
```

**Comment by geordzNZ** [comment]
yeah agreed, I just for some reason had a mind blank on it and went the other way
