### ISSUE TITLE
use result of condition to set booleans

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/GuessingGame#5]
https://github.com/geordzNZ/GuessingGame/blob/1b257f380ea4d48b6d90754f000e9c84222d6312/GuessingGame/Program.cs#L38-L42
If a bool flag purely relies on one condition and is not used of overridden elsewhere it is shorter and easier to read when you just assign  the result of the condition to it:
```
bool closeGuess = (Math.Abs(targetNumber - guessedNumber) <= CLOSE_GUESS_DIFFERENCE);
```

**Comment by geordzNZ** [comment]
Ok understood, can see how that is easier to read, and less to type.

Closing this now though as a previous refactor, got rid of closeGuess anyways
