### ISSUE TITLE
Simplify code

### ISSUE THREAD

**Issue by henrikmdev** [geordzNZ/GuessingGame#7]
https://github.com/geordzNZ/GuessingGame/blob/1b257f380ea4d48b6d90754f000e9c84222d6312/GuessingGame/Program.cs#L38-L42
https://github.com/geordzNZ/GuessingGame/blob/1b257f380ea4d48b6d90754f000e9c84222d6312/GuessingGame/Program.cs#L47-L52
https://github.com/geordzNZ/GuessingGame/blob/1b257f380ea4d48b6d90754f000e9c84222d6312/GuessingGame/Program.cs#L57-L62

Combining the ideas from issues #3 and #5, you can actually bring all these lines after the check on if the guess was too high or too low. After implementing Michael's suggestions, you can just have one if statement to check if the guess was close. If it is close, then tell the user. Then, you can get rid of the closeGuess variable.

**Comment by geordzNZ** [comment]
yeah, looks a lot cleaner now as per fix from #3
