### ISSUE TITLE
Alternative idea

### ISSUE THREAD

**Issue by henrikmdev** [geordzNZ/GuessingGame#8]
https://github.com/geordzNZ/GuessingGame/blob/1b257f380ea4d48b6d90754f000e9c84222d6312/GuessingGame/Program.cs#L25

This is just my preference, but I prefer to simplify the condition for the while loop to focus on just one thing. It's more readable in my opinion that way.

For example, I would focus on only this condition (guessCounter < ALLOWED_GUESSES), then exit the while loop if the user guesses correctly using a break.

**Comment by geordzNZ** [comment]
noted and tried it ... I like it, so added it in :-)
